// Search
export const INITIAL_SEARCH = 'INITIAL_SEARCH'
export const NEXT_SEARCH_PAGE = 'NEXT_SEARCH_PAGE'
export const PREVIOUS_SEARCH_PAGE = 'PREVIOUS_SEARCH_PAGE'
export const TITLE_SEARCH = 'TITLE_SEARCH'
export const CLEAR_ALL = 'CLEAR_ALL'

// USER
export const GET_USER_INFO = 'GET_USER_INFO'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_USER_COLLECTIONS = 'GET_USER_COLLECTIONS'
export const GET_FAV_INFO = 'GET_FAV_INFO'
export const CLEAR_FAV_INFO = 'CLEAR_FAV_INFO'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'